from __future__ import annotations

from pathlib import Path
from typing import Any

import chromadb
from chromadb.api.types import (
    Metadata,
    Metadatas,
)

from app.rag.embedding_service import (
    EmbeddingService,
)
from app.rag.models import (
    DocumentChunk,
    RetrievalHit,
)

# =========================================================
# CONSTANTS
# =========================================================


DEFAULT_COLLECTION = "support_policies"


# =========================================================
# METADATA TYPE HELPERS
# =========================================================


def _metadata_str(
    metadata: Metadata,
    key: str,
) -> str:
    """
    Read a string metadata value safely.

    Chroma's Metadata type supports multiple possible
    value types, therefore we validate at runtime before
    using the value as a string.
    """

    value = metadata.get(key)

    if not isinstance(
        value,
        str,
    ):
        raise TypeError(
            f"Expected metadata '{key}' to be str, got {type(value).__name__}"
        )

    return value


def _metadata_int(
    metadata: Metadata,
    key: str,
) -> int:
    """
    Read an integer metadata value safely.

    bool is explicitly rejected because bool is a subclass
    of int in Python.
    """

    value = metadata.get(key)

    if isinstance(
        value,
        bool,
    ):
        raise TypeError(f"Expected metadata '{key}' to be int, got bool")

    if not isinstance(
        value,
        int,
    ):
        raise TypeError(
            f"Expected metadata '{key}' to be int, got {type(value).__name__}"
        )

    return value


# =========================================================
# VECTOR STORE
# =========================================================


class PolicyVectorStore:
    """
    Chroma-based vector store for customer support
    policy knowledge.

    Responsibilities:

        1. Persist embeddings
        2. Store document chunks
        3. Store chunk metadata
        4. Perform semantic similarity search
        5. Return strongly typed RetrievalHit objects

    Important:

    Embeddings are generated by EmbeddingService.

    Chroma is responsible for storing and searching
    those vectors.
    """

    def __init__(
        self,
        db_path: str | Path = "chroma_db",
        collection_name: str = DEFAULT_COLLECTION,
        embedding_service: EmbeddingService | None = None,
    ) -> None:

        self.db_path = Path(db_path)

        self.collection_name = collection_name

        self.embedding_service = embedding_service or EmbeddingService()

        # -------------------------------------------------
        # Persistent Chroma client
        # -------------------------------------------------

        self.client = chromadb.PersistentClient(path=str(self.db_path))

        # -------------------------------------------------
        # Get existing collection or create it
        # -------------------------------------------------

        self.collection = self.client.get_or_create_collection(
            name=self.collection_name
        )

    # =====================================================
    # RESET COLLECTION
    # =====================================================

    def reset_collection(self) -> None:
        """
        Completely remove the existing Chroma collection
        before rebuilding the vector index.

        Important:
        Never silently ignore reset failures because stale
        chunks can remain in the vector database and corrupt
        retrieval evaluation.
        """

        collections = self.client.list_collections()

        existing_names: set[str] = set()

        for collection in collections:
            if isinstance(
                collection,
                str,
            ):
                existing_names.add(collection)

            else:
                existing_names.add(collection.name)

        if self.collection_name in existing_names:
            self.client.delete_collection(name=self.collection_name)

        self.collection = self.client.get_or_create_collection(
            name=self.collection_name
        )

    # =====================================================
    # INDEX DOCUMENT CHUNKS
    # =====================================================

    def index_chunks(
        self,
        chunks: list[DocumentChunk],
        reset: bool = False,
    ) -> int:
        """
        Convert document chunks to embeddings and store
        them in Chroma.

        Each Chroma record contains:

            id
            embedding
            document text
            metadata

        Example metadata:

            {
                "policy_id": "REFUND_POLICY",
                "title": "Refund and Return Policy",
                "source": "refund_policy.md",
                "chunk_index": 0
            }
        """

        if reset:
            self.reset_collection()

        if not chunks:
            return 0

        # -------------------------------------------------
        # Text that will be embedded
        # -------------------------------------------------

        texts = [chunk.content for chunk in chunks]

        # -------------------------------------------------
        # Generate embeddings
        # -------------------------------------------------

        embeddings = self.embedding_service.embed_documents(texts)

        # -------------------------------------------------
        # Unique Chroma IDs
        # -------------------------------------------------

        ids = [chunk.chunk_id for chunk in chunks]

        # -------------------------------------------------
        # Strongly typed Chroma metadata
        # -------------------------------------------------

        metadatas: Metadatas = []

        for chunk in chunks:
            metadata: Metadata = {
                "policy_id": (chunk.policy_id),
                "title": (chunk.title),
                "source": (chunk.source),
                "chunk_index": (chunk.chunk_index),
            }

            metadatas.append(metadata)

        # -------------------------------------------------
        # Store records
        # -------------------------------------------------

        self.collection.upsert(
            ids=ids,
            embeddings=embeddings,
            documents=texts,
            metadatas=metadatas,
        )

        return len(chunks)

    # =====================================================
    # SEMANTIC SEARCH
    # =====================================================

    def search(
        self,
        query: str,
        n_results: int = 3,
        where: dict[str, Any] | None = None,
    ) -> list[RetrievalHit]:
        """
        Search Chroma using semantic similarity.

        Flow:

            user query
                ↓
            query embedding
                ↓
            Chroma nearest-neighbour search
                ↓
            RetrievalHit objects
        """

        query = query.strip()

        if not query:
            raise ValueError("Query cannot be empty")

        if n_results <= 0:
            raise ValueError("n_results must be greater than zero")

        # -------------------------------------------------
        # Empty DB check
        # -------------------------------------------------

        total_records = self.collection.count()

        if total_records == 0:
            return []

        # -------------------------------------------------
        # Create query embedding
        # -------------------------------------------------

        query_embedding = self.embedding_service.embed_query(query)

        # Cannot request more than what exists
        actual_results = min(
            n_results,
            total_records,
        )

        # -------------------------------------------------
        # Query arguments
        # -------------------------------------------------

        query_kwargs: dict[
            str,
            Any,
        ] = {
            "query_embeddings": [query_embedding],
            "n_results": (actual_results),
            "include": [
                "documents",
                "metadatas",
                "distances",
            ],
        }

        # Metadata filtering is optional.
        if where is not None:
            query_kwargs["where"] = where

        # -------------------------------------------------
        # Chroma search
        # -------------------------------------------------

        result = self.collection.query(**query_kwargs)

        # -------------------------------------------------
        # Extract first query batch
        #
        # Chroma returns nested lists because it supports
        # querying multiple embeddings at once.
        # -------------------------------------------------

        ids = result["ids"][0] if result["ids"] else []

        documents_result = result.get("documents")

        metadatas_result = result.get("metadatas")

        distances_result = result.get("distances")

        documents = documents_result[0] if documents_result else []

        metadatas = metadatas_result[0] if metadatas_result else []

        distances = distances_result[0] if distances_result else []

        # -------------------------------------------------
        # Convert Chroma records into our domain model
        # -------------------------------------------------

        hits: list[RetrievalHit] = []

        for (
            chunk_id,
            document,
            metadata,
            distance,
        ) in zip(
            ids,
            documents,
            metadatas,
            distances,
        ):
            # ---------------------------------------------
            # Defensive checks
            # ---------------------------------------------

            if metadata is None:
                continue

            if document is None:
                continue

            if distance is None:
                continue

            # ---------------------------------------------
            # Convert Chroma metadata safely
            # ---------------------------------------------

            policy_id = _metadata_str(
                metadata,
                "policy_id",
            )

            title = _metadata_str(
                metadata,
                "title",
            )

            source = _metadata_str(
                metadata,
                "source",
            )

            chunk_index = _metadata_int(
                metadata,
                "chunk_index",
            )

            # ---------------------------------------------
            # Build typed retrieval result
            # ---------------------------------------------

            hit = RetrievalHit(
                chunk_id=chunk_id,
                policy_id=policy_id,
                title=title,
                source=source,
                chunk_index=chunk_index,
                content=document,
                distance=float(distance),
            )

            hits.append(hit)

        return hits

    # =====================================================
    # COUNT
    # =====================================================

    def count(
        self,
    ) -> int:
        """
        Number of vectors currently stored.
        """

        return self.collection.count()
